name: Pack Package

on:
  workflow_call:
    inputs:
      package-name:
        description: 'Name of the package to pack'
        required: true
        type: string

jobs:
  pack-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with: 
            path: "Packages/${{inputs.package-name}}/package.json"
            prop_path: "version"
            
      - run: echo ${{steps.version.outputs.prop}} 
    
      - name: Set Environment Variables
        run: |
          echo "zipFile=${{ inputs.package-name }}-${{ steps.version.outputs.prop }}".zip >> $GITHUB_ENV
          echo "unityPackage=${{ inputs.package-name }}-${{ steps.version.outputs.prop }}.unitypackage" >> $GITHUB_ENV
        
      - name: Create Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "Packages/${{inputs.package-name}}/"
          filename: "../../${{env.zipFile}}" # make the zip file two directories up, since we start two directories in above
          
      - run: find "Packages/${{inputs.package-name}}/" -name \*.meta >> metaList
          
      - name: Create UnityPackage
        uses: pCYSl5EDgo/create-unitypackage@e28c7a4616b2754c564b0a959a03b3c89b756fdb
        with:
          package-path: ${{ env.unityPackage }}
          include-files: metaList

      - name: Add Summary
        run: |
          echo "# Package ${{inputs.package-name}}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "saved as"
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- ${{ env.zipFile }}" >> $GITHUB_STEP_SUMMARY
          echo "- ${{ env.unityPackage }}" >> $GITHUB_STEP_SUMMARY    
        
      - name: Make Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          tag_name: ${{ steps.version.outputs.prop }}
          files: |
            ${{ env.zipFile }}
            ${{ env.unityPackage }}
#            Packages/${{ inputs.package-name }}/package.json

      - name: Make Pre-Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        if: startsWith(github.ref, 'refs/heads/dev')
        with:
          tag_name: ${{ steps.version.outputs.prop }}
          draft: true
          prerelease: true
          files: |
            ${{ env.zipFile }}
            ${{ env.unityPackage }}
        #            Packages/${{ inputs.package-name }}/package.json

