name: Build Release

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - Packages/sh.orels.shaders/**
      - Packages/sh.orels.shaders.generator/**
      - Packages/sh.orels.shaders.inspector/**

env:
  shadersPackageName: "sh.orels.shaders"
  inspectorPackageName: "sh.orels.shaders.inspector"
  generatorPackageName: "sh.orels.shaders.generator"

jobs:
  pack-shaders:
    uses: ./.github/workflows/pack-package.yml
    with:
      package-name: "sh.orels.shaders"

  pack-inspector:
    uses: ./.github/workflows/pack-package.yml
    with:
      package-name: "sh.orels.shaders"

  pack-generator:
    uses: ./.github/workflows/pack-package.yml
    with:
      package-name: "sh.orels.shaders"

  pack-repo:
    uses: ./.github/workflows/pack-repo.yml

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
    
  #     - name: Checkout
  #       uses: actions/checkout@v3
    
  #     - name: Pack Shaders
  #       uses: ./.github/workflows/pack-package.yml
  #       with:
  #         package-name: ${{ env.shadersPackageName }}

  #     - name: Pack Inspector
  #       uses: ./.github/workflows/pack-package.yml
  #       with:
  #         package-name: ${{ env.inspectorPackageName }}

  #     - name: Pack Generator
  #       uses: ./.github/workflows/pack-package.yml
  #       with:
  #         package-name: ${{ env.generatorPackageName }}
      
  #     - name: Pack Repo
  #       uses: ./.github/workflows/pack-repo.yml
